### ISSUE TITLE
scripts/gen_random_example.py lacks  “./main_check_multirobot” program

### ISSUE THREAD

**Issue by ucas-zihaowang** [IMRCLab/db-CBS#122]
Hello, I want to generate more instances using scripts/gen_random_example.py, but this Python script lacks a C++ program called "main_check_multirobot".
By searching the entire project, I found that CMakeLists.txt contains the compile code for the main_check_multirobot program, but the author commented it out.
Can you provide the main_check_multirobot.cpp source code? @akmaralAW, Thanks!

**Comment by akmaralAW** [comment]
Hi @ucas-zihaowang, 
Please checkout to benchmark_icra24 branch, I believe src/check_trajectory_multirobot.cpp is the file you are looking for. 
Good luck.
